name: Test Release flow with Docker-compose

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        options:
          - dev

jobs:
  check-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if Docker image exists
        run: |
          # Attempt to pull the Docker image
          if docker pull kolmanfreecss/jenkins-git:0.2.0-SNAPSHOT; then
            echo "Docker image kolmanfreecss/jenkins-git:0.2.0-SNAPSHOT exists on Docker Hub."
          else
            echo "Docker image kolmanfreecss/jenkins-git:0.2.0-SNAPSHOT does not exist on Docker Hub."
            exit 1
          fi
